POST {{host}}/proyecto
Authorization: Bearer {{token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "codigo":"011",
  "nombre":"proyecto-prueba-4",
  "fecha_inicio":"01/01/2021",
  "fecha_fin":"01/03/2021",
  "municipio_inicio":"8001",
  "ubicacion_inicial":"ubicacion-1",
  "municipio_final":"8001",
  "ubicacion_final":"ubicacion-2",
  "horas_laboral":"8",
  "temperatura":"36",
  "propietario_dobletroque":"Mixto",
  "duracion_proyecto":"160",
  "cantidad_vehiculo_propio":"9",
  "cantidad_vehiculo_alquilado":"5",
  "valor_metrocubico_propio":"1000",
  "valor_metrocubico_alquilado":"1500",
  "valor_contrato":"100000000000",
  "valor_anticipo_contrato":"200000",

   "tiposVias": [
           {"tipovia_id": "1" },
           {"tipovia_id": "2" },
           {"tipovia_id": "4", "otros": "bambu"}
       ],

   "rellenos": [
           {"tipo_material_id": "1"}

      ],
    "costoServicio":[
         {
             "servicio_id": "4",
             "otro_servicio": "prueba servicio7",
             "proveedor_id": "1",
             "forma_pago": "Diaria",
             "medio_pago": "Efectivo",
             "otro_medio_pago":"",
             "pago_a_realizar": "Esercon",
             "detalle":[
                    {

                        "tipo_costo_servicio_id":"4",
                        "otro_costo_servicio":"almuerzo ",
                        "valor":"10000"
                     }
                  ]
         },
          {
             "servicio_id": "4",
             "otro_servicio": "prueba servicio8",
             "proveedor_id": "1",
             "forma_pago": "Diaria",
             "medio_pago": "Efectivo",
             "otro_medio_pago":"",
             "pago_a_realizar": "Esercon",
             "detalle":[
                    {

                        "tipo_costo_servicio_id":"4",
                        "otro_costo_servicio":"almuerzo ",
                        "valor":"10000"
                     }
                  ]
         }
    ],
    "condiciones_economicas":[
                                {
                                    "nombre_condicion_economica_id":"1",
                                    "otro_condicion_econoimica":"",
                                    "pago_a_realizar":"Proveedor",
                                    "forma_pago":"Semanal",
                                    "medio_pago":"Tranferencia",
                                    "otro_medio_pago":""
                                }

                            ],
    "datos_operacion":{

                            "Consumo de combustible por día":"",
                            "Consumo de lubricante por día":"",
                            "Consumo de refrigerante":"",
                            "Consumo de grasa":"",
                            "Consumo de llantas por día":"",
                            "Pago de peajes":"",
                            "Pago conductor por día":"",
                            "Pago de hidratación por día":"",
                            "Pago parqueadero por día":"",
                            "Pago SOAT por día":"",
                            "Pago Tecnomecánica por día":"",
                            "Pago de seguro todo riesgo por día":"",
                            "Pago cuota leasing por día":"",
                            "Pago lavado por día":"",
                            "Pago mantenimiento por día":"",
                            "Pago Administración por día"  :""
    },
    "datos_administracion":{
                            "Salario conductor por dia":"",
                            "S. ger. Nal. Operaciones por dia":"",
                            "S. ger. Regional operaciones por dia":"",
                            "S. ger. Recursos humanos por dia":"",
                            "S. asistente rec humanos por día":"",
                            "Salario gerencia administrativa por día":"",
                            "Salario supervidor asignado por día":"",
                            "Pago arriendo oficina por día":"",
                            "Pago servicios oficina por día":"",
                            "Pago alojamiento por día":"",
                            "Pago alimentación por día":"",
                            "Pago alquiler de camionetas por día":"",
                            "Pago tiquetes aéreos por día":"",
                            "Pago transporte terrestre por día":"",
                            "Pago gasolina camionetas por día":"",
                            "Pago papelería por día":"",
                            "Pago insumos oficina por día":"",
                            "Pago otros gastos oficina":""
    }


}

###

POST {{host}}/costoServicio/2
Authorization: Bearer {{token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest


{
    "servicio_id": "1",
    "proveedor_id": "1",
    "forma_pago": "Diaria",
    "medio_pago": "Efectivo",
    "otro_medio_pago":"",
    "pago_a_realizar": "Esercon"

}

###
GET {{host}}/servicios
Authorization: Bearer {{token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

###
POST {{host}}/detalleCosto
Authorization: Bearer {{token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "proyectoCostoServicio": "1",
    "tipoCostoServicio": "",
    "valor":""
        }

###
POST {{host}}/tempAdds
Authorization: Bearer {{token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "servicio_id": "1",
    "nombre": "archivo prueba"
}

### DEtalle costo  el nombre del costo
GET {{host}}/detalleCosto
Authorization: Bearer {{token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest


### Condiciones Economicas

GET {{host}}/condicionesEconomicas
Authorization: Bearer {{token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest


###
GET {{host}}/consumo_pago_estimado
Authorization: Bearer {{token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

###
PATCH {{host}}/proyecto/
Authorization: Bearer {{token}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{

}
